# Generated by Django 2.2.3 on 2019-09-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('музей', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='item', to='музей.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='музей.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Locker',
        ),
    ]
