# Generated by Django 2.2.3 on 2019-09-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('музей', '0003_auto_20190923_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_place', to='музей.Place'),
        ),
    ]
