# Generated by Django 2.2.3 on 2019-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('музей', '0004_auto_20190924_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['mark']},
        ),
        migrations.AddField(
            model_name='item',
            name='getting',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
